### ISSUE TITLE
XHR(XMLHttpRequest) API 를 Fetch API로 대체 제안

### ISSUE THREAD

**Issue by getCurrentThread** [flaxinger/BaekjoonHub#16]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**
- 현재 XMLHttpRequest API를 사용하여 메인 쓰레드 내에서 동기화된 네트워크 호출 방식을 사용하므로 경고가 발생
- 차후 추가 기능인 사용자의 모든 코드를 github에 업로드하는 기능 구현에 제한사항이 발생할 것으로 여겨짐

**Describe the solution you'd like**
- 네트워크 통신 방식을 XMLHttpRequest API 에서 Fetch API로 변경 제안. [(변경할 참조 커밋 지점)](https://github.com/getCurrentThread/BaekjoonHub/commit/c222539c94e4edb6de0136a3c12192509ddc88ff)

**Describe alternatives you've considered**
- Promise, 비동기 처리가 가능한 Axios API 활용 제안
- setTimeout 등의 추가 쓰레드를 호출하여 임의 처리
- 익스텐션 내의 백그라운드 처리에 이벤트를 호출하여 처리하도록 구조 변경

**Additional context**
![image](https://user-images.githubusercontent.com/31976959/147813173-52651580-8c66-4faa-b644-fec699ce3b1c.png)

**Comment by flaxinger** [comment]
이에 대한 저의 의견은 아래와 같습니다.

**1. Axios & Promise**
기존 LeetHub의 소스코드에서 XMLHttpRequest를 사용했었는데, 언급하신대로 향후 기능을 고려하여 전체적으로 Axios로 바꾸는 것이 좋아보입니다. 다만 XMLHttpRequest로도 비동기 요청이 가능하기는 합니다.

**2. 비동기 처리**
비동기 처리와 관련하여 기존에 조금 고민을 하였는데요, 현재 첨부하신 코드에는 다음의 문제가 있을 수 있습니다.

```
findData(){     // line 372, 625
  findFromResultTable() 함수의 findSolvedAPI() 함수 비동기 처리
  findProblemDescription() 함수 비동기 처리
  findCode() 함수 비동기 처리
  
  readme  작성 시점에 title, language, level 등 메타 데이터 undefined
}

ready() 함수 false 리턴// line 379

findData() 다시 호출 // line 372
-> 문제 1. 현재 readme가 '+='로 append되는 형식이기에 findData가 두번 실행되면 중복 텍스트가 생기게 됩니다. 
이와 관련하여 아래 첨부된 테스트 레파지토리를 확인 부탁드립니다. 
단 이 부분은 reamde의 첫 문장을 '='로 초기화하면 해결됩니다.
-> 문제 2. findData 반복 실행의 경우 기존에 이미 파싱했던 데이터 값도 다시 파싱하므로 실행 시간이 늘어나고 자원 낭비가 발생합니다. 
```
[테스트 레파지토리](https://github.com/flaxinger/getCurThreadTest)

**3. 해결방법**
우선 간략하게 함수간 Dependency를 요약하자면 아래와 같습니다. 
```
findData(){
	
	findFromResultTable(){
		// get memory
		// get runtime
		// get language
		// get SubmissionId
		// get ProblemId
		findSolvedAPI(){
			// needs problemId
			// gets title
			// gets level
			// gets message
			// gets category
		}
	}
	findProblemDescription(){
		// needs problemId
		// gets problemDescription
	}

	findCode(){
		// needs submissionId 
		// gets code
	}

        // README.md 작성
	  // needs title (findSolvedAPI Dependency)
	  // needs language
	  // needs level (findSolvedAPI Dependency)
	  // needs title (findSolvedAPI Dependency)
	  // needs problemId
	  // needs memory
	  // needs runtime
	  // needs category (findSolvedAPI Dependency)
	  // needs problemDescription (findProblemDescription Dependency)
}
```
핵심은 reademe를 작성하는 시점에 모든 프로미스가 이행되어야만 정상작동 하는데, findSolvedAPI와 findProblemDescription의 promise를 별도로 처리하면 이 둘의 promise가 모두 이행된 시점이 언제인지 알기 어렵습니다. 따라서 아래 txt 파일과 같이 코드를 바꿨으니 확인 부탁드립니다. 요약하자면 Promise.all()을 통해 모든 Promise가 이행된 후 readme 작성 및 깃업로드가 실행되도록 처리하였습니다.

아직 다듬어지지는 않았지만 beginUpload(line 382), findData(line 631), findWithPromise(line 689) 함수를 확인하시면 대략적인 파악을 하실 수 있을 것 같습니다. 더불어  escapeHTML(line 918) replace 처리가 character reference를 변환하는 것이 아닌 character reference로 변환하도록 되어있어 변경하였습니다.

아래는 수정사항을 담은 파일로, 확인 부탁드립니다.
[currentThreadFeedback.txt](https://github.com/flaxinger/BaekjoonHub/files/7796464/currentThreadFeedback.txt)

제안 주신 부분이라 제가 커밋을 날리기가 조금 그래서 참고하시고 PR 주시면 검토 후 승인하겠습니다. 
더불어 공지 없이 파일 구조가 바뀌어 당황하셨을 수도 있는데 이 부분에 대해 양해를 구합니다. 
혹 수정할 시간적 여유가 부족하시다면 제가 직접 변경하도록 하겠습니다.

혹시 코드에 문제가 있거나 지적할 부분이  있다면 알려주세요.

적극적인 제안 너무 감사드립니다!

새해 복 많이 받으세요!

**Comment by getCurrentThread** [comment]
상세히 검토해주셔서 감사합니다. 😃 

피드백 주신 내용, 일부 처리와 각 함수 의존성 및 주신 테스트 레포지토리까지 잘 확인하였습니다.

확인해주신 문자열 추가로 인하여 발생하는 [문제 예시](https://github.com/flaxinger/getCurThreadTest/tree/main/한-줄로-서기)는 테스트 계정으로 확인하였을 때에 발견치 못하였는데, 상세히 확인해주셔서 감사합니다.

수정사항이 반영된 코드 내에 큰 이상은 없는 것으로 확인됩니다. 

추가적으로 코드 일부 정리를 위해 다음과 같이 처리도 제안해봅니다.


### 이전코드
```
Promise.all([DescriptionParse, CodeParse, SolvedAPI])
      .then(promiseArray => Promise.all([promiseArray[0].text(), promiseArray[1].text(), promiseArray[2].json()]))
      .then(promiseData => {
        let descriptionText = promiseData[0];
        let codeText = promiseData[1];
        let solvedJson = promiseData[2];
        /* Get Question Description */
        let questionDescription = "";
```


### 이후코드
```
Promise.all([DescriptionParse, CodeParse, SolvedAPI])
      .then(([despResponse, codeResponse, solvedResponse]) => Promise.all([despResponse.text(), codeResponse.text(), solvedResponse.json()]))
      .then(([descriptionText, codeText, solvedJson]) => {

        /* Get Question Description */
        let questionDescription = "";
```


추가적으로 기존 코드에 업로드 실패 시에 빨간색 체크 표시를 하면서 실패했다는 표시로 처리하는 부분이 있는데, 
그 부분도 Promise.all 에 .catch() 로 해서 예외 처리를 하면 좋을 것 같습니다.


늦은 시간에 회신드려 송구스럽습니다.

새해 복 많이 받으세요~! 🎊 🆕 📆

**Comment by flaxinger** [comment]
좋습니다. 이게 더 깔끔해보이네요.

catch문도 넣으면 좋을 것 같습니다!

고생 많으셨어요!
